language: node_js
node_js:
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libreoffice
  - sudo apt-get install -y unoconv
  - sudo apt-get install -y imagemagick
before_script:
  - soffice --nologo --headless --nofirststartwizard --accept='socket,host=127.0.0.1,port=2220,tcpNoDelay=1;urp;StarOffice.Service' > /dev/null 2>&1 &
  - npm install -g mocha
  - npm install -g istanbul
  - npm install -g codeclimate-test-reporter
addons:
    code_climate:
        repo_token: 5708ac2ce7800648d7f36b2b5150d4aeb9ed16eb6ffd967ff555e56743842b8c
after_script:
  - codeclimate-test-reporter < lcov.info